---
all:
  children:
    kubernetes:
      hosts:
        node-1:
          ansible_host: 65.109.229.12
          ansible_user: root
          ansible_ssh_private_key_file: ../vmkey
        node-2:
          ansible_host: 37.27.253.78
          ansible_user: root
          ansible_ssh_private_key_file: ../vmkey
        node-3:
          ansible_host: 77.42.23.65
          ansible_user: root
          ansible_ssh_private_key_file: ../vmkey
      vars:
        # RKE configuration
        rke_version: "v1.8.6"
        kubernetes_version: "v1.30.14-rancher1-1"

