{{- if .Values.zookeeper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: client
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}-headless
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: client
  - port: 2888
    targetPort: 2888
    protocol: TCP
    name: follower
  - port: 3888
    targetPort: 3888
    protocol: TCP
    name: election
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
{{- end }}
