{{- if .Values.nifi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi-platform.fullname" . }}-nifi
  labels:
    {{- include "nifi-platform.nifi.labels" . | nindent 4 }}
  {{- with .Values.nifi.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.nifi.service.type }}
  {{- if and (eq .Values.nifi.service.type "NodePort") .Values.nifi.service.nodePort }}
  ports:
  - port: {{ .Values.nifi.service.port }}
    targetPort: {{ .Values.nifi.properties.nifi.web.http.port }}
    protocol: TCP
    name: http
    nodePort: {{ .Values.nifi.service.nodePort }}
  {{- else }}
  ports:
  - port: {{ .Values.nifi.service.port }}
    targetPort: {{ .Values.nifi.properties.nifi.web.http.port }}
    protocol: TCP
    name: http
  {{- end }}
  selector:
    {{- include "nifi-platform.nifi.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi-platform.fullname" . }}-nifi-headless
  labels:
    {{- include "nifi-platform.nifi.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.nifi.properties.nifi.web.http.port }}
    targetPort: {{ .Values.nifi.properties.nifi.web.http.port }}
    protocol: TCP
    name: http
  - port: {{ .Values.nifi.properties.nifi.cluster.node.protocol.port }}
    targetPort: {{ .Values.nifi.properties.nifi.cluster.node.protocol.port }}
    protocol: TCP
    name: cluster
  selector:
    {{- include "nifi-platform.nifi.labels" . | nindent 4 }}
{{- end }}

