COMPUTED VALUES:
global:
  imagePullSecrets: []
  imageRegistry: ""
  namespace: data-platform-integration
nifi:
  affinity: {}
  cluster:
    autoscaling:
      behavior:
        scaleDown:
          policies:
          - periodSeconds: 60
            type: Percent
            value: 50
          stabilizationWindowSeconds: 300
        scaleUp:
          policies:
          - periodSeconds: 60
            type: Percent
            value: 100
          - periodSeconds: 60
            type: Pods
            value: 2
          selectPolicy: Max
          stabilizationWindowSeconds: 0
      enabled: false
      maxReplicas: 10
      minReplicas: 3
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    enabled: true
    nodeCount: 3
    zookeeper:
      enabled: true
      external:
        connectionString: zookeeper:2181
        enabled: false
      image:
        pullPolicy: IfNotPresent
        repository: zookeeper
        tag: "3.9"
      replicas: 3
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
      storage:
        size: 2Gi
      storageClassName: longhorn
  enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: apache/nifi
    tag: 2.7.1
  ingress:
    annotations: {}
    className: nginx
    enabled: true
  jvm:
    additionalJavaArgs: ""
    heapSize: 1g
    maxDirectMemory: 512m
  keycloak:
    adminGroup: nifi-admin
    clientId: nifi
    clientSecret: ""
    enabled: false
    realm: data-platform
    url: https://keycloak.data-platform.local/auth
    userGroup: nifi-user
  nodeSelector: {}
  podAnnotations: {}
  properties:
    nifi:
      cluster:
        flow:
          election:
            max:
              candidates: "1"
              wait:
                time: 300 secs
        is:
          node: "true"
        node:
          connection:
            timeout: 30 sec
          max:
            concurrent:
              requests: "100"
          protocol:
            port: "8082"
          read:
            timeout: 30 sec
      content:
        repository:
          archive:
            max:
              retention:
                period: 30 days
          directory:
            default: ./content_repository
      flowfile:
        repository:
          directory:
            default: ./flowfile_repository
      provenance:
        repository:
          directory:
            default: ./provenance_repository
          implementation: org.apache.nifi.provenance.WriteAheadProvenanceRepository
          max:
            storage:
              size: 10 GB
              time: 24 hours
      remote:
        input:
          secure: "false"
          socket:
            port: "10443"
      security:
        user:
          authorizer: managed-authorizer
          login:
            identity:
              provider: keycloak-provider
          oidc:
            additional:
              scopes: ""
            claim:
              identifying:
                user: preferred_username
            client:
              id: ""
              secret: ""
            connect:
              timeout: 5 secs
            discovery:
              url: ""
            fallback:
              claims:
                identifying:
                  user: email
            preferred:
              jwk:
                url: ""
            read:
              timeout: 5 secs
            scope: openid profile email
            truststore:
              strategy: JDK
      state:
        management:
          config:
            file: ./conf/state-management.xml
          provider:
            cluster: zk-provider
      web:
        http:
          port: "8080"
        https:
          host: 0.0.0.0
          port: "8443"
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
  security:
    enabled: true
    ssl:
      enabled: false
      keystorePassword: ""
      truststorePassword: ""
  service:
    annotations: {}
    nodePort: null
    port: 8080
    type: ClusterIP
  storage:
    accessModes:
    - ReadWriteOnce
    size: 2Gi
    stateSize: 2Gi
    storageClassName: longhorn
    type: persistentVolumeClaim
  tolerations: []
nifiRegistry:
  affinity: {}
  database:
    h2:
      dataDir: ./database
      storage:
        size: 2Gi
    postgresql:
      database: nifi_registry
      host: postgresql.data-platform-storage.svc.cluster.local
      password: ""
      port: 5432
      ssl: false
      username: nifi_registry
    type: h2
  enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: apache/nifi-registry
    tag: 1.23.2
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    className: nginx
    enabled: true
    hosts:
    - host: nifi-registry.data-platform.local
      paths:
      - path: /
        pathType: Prefix
    tls: []
  keycloak:
    adminGroup: nifi-registry-admin
    clientId: nifi-registry
    clientSecret: ""
    enabled: false
    realm: data-platform
    url: https://keycloak.data-platform.local/auth
    userGroup: nifi-registry-user
  nodeSelector: {}
  podAnnotations: {}
  properties:
    nifi:
      registry:
        db:
          driverClass: ""
          maxConnections: "5"
          password: ""
          url: ""
          username: ""
        security:
          user:
            authorizer: managed-authorizer
            login:
              identity:
                provider: keycloak-provider
            oidc:
              claim:
                identifying:
                  user: preferred_username
              client:
                id: ""
                secret: ""
              discovery:
                url: ""
              fallback:
                claims:
                  identifying:
                    user: email
              scope: openid profile email
        web:
          http:
            port: "18080"
          https:
            host: 0.0.0.0
            port: "18443"
  replicas: 1
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  security:
    enabled: true
    ssl:
      enabled: false
      keystorePassword: ""
      truststorePassword: ""
  service:
    annotations: {}
    port: 18080
    type: ClusterIP
  storage:
    accessModes:
    - ReadWriteOnce
    size: 2Gi
    storageClassName: longhorn
    type: persistentVolumeClaim
  tolerations: []
podSecurityPolicy:
  enabled: false
rbac:
  create: true
secrets:
  database:
    create: false
    postgresqlPassword: ""
  keycloak:
    create: true
    nifiClientSecret: ""
    nifiRegistryClientSecret: ""
  ssl:
    create: false
    keystorePassword: ""
    truststorePassword: ""
serviceAccount:
  annotations: {}
  create: true
  name: ""
